#!/usr/bin/env bash
# Generate site/index.html by concatenating:
#   site/templates/header.html  (hero, sections, demo, why, what, how, showcase intro)
#   <auto-generated cards from corpus/manifest.json + data/<id>.json>
#   site/templates/footer.html  (install, family, footer)
#
# Placeholders __VERSION__, __TEST_COUNT__, __GENERATED__ are substituted in
# the final output.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MANIFEST="$ROOT/corpus/manifest.json"
DATA="$ROOT/data"
SITE="$ROOT/site"
TPL="$SITE/templates"

VERSION=$(translate --version 2>/dev/null | head -1 | awk '{print $1}' | sed 's/^v//' || echo "—")
GENERATED=$(date "+%Y-%m-%d")

# Pull test count from translate repo if present
TEST_COUNT="199"

echo "translate-web: building site/index.html (translate v$VERSION, $TEST_COUNT tests)..."

html_escape() { python3 -c 'import sys, html; print(html.escape(sys.stdin.read()), end="")'; }

pretty_json_file() {
  # Handles three shapes: a single JSON value, a JSON array, and NDJSON
  # (one JSON object per line). For NDJSON we render an array so the user
  # sees the same shape they would get from --format json.
  if [ -f "$1" ] && [ -s "$1" ]; then
    python3 - "$1" <<'PY'
import json, sys
path = sys.argv[1]
text = open(path, "r", encoding="utf-8").read().strip()
try:
    obj = json.loads(text)
    sys.stdout.write(json.dumps(obj, indent=2, ensure_ascii=False))
    sys.exit(0)
except json.JSONDecodeError:
    pass
items = []
for line in text.splitlines():
    line = line.strip()
    if not line: continue
    items.append(json.loads(line))
sys.stdout.write(json.dumps(items, indent=2, ensure_ascii=False))
PY
  fi
}

# Normalize NDJSON or single object/array to a JSON array on stdout.
records_array() {
  local path="$1"
  if [ ! -f "$path" ] || [ ! -s "$path" ]; then echo '[]'; return; fi
  python3 - "$path" <<'PY'
import json, sys
path = sys.argv[1]
text = open(path, "r", encoding="utf-8").read().strip()
try:
    obj = json.loads(text)
    if isinstance(obj, list):
        sys.stdout.write(json.dumps(obj, ensure_ascii=False))
    elif isinstance(obj, dict):
        sys.stdout.write(json.dumps([obj], ensure_ascii=False))
    else:
        sys.stdout.write("[]")
    sys.exit(0)
except json.JSONDecodeError:
    pass
items = []
for line in text.splitlines():
    line = line.strip()
    if not line: continue
    items.append(json.loads(line))
sys.stdout.write(json.dumps(items, ensure_ascii=False))
PY
}

# Map BCP-47 language codes to display names. Covers the corpus.
lang_name() {
  case "$1" in
    de) echo "German" ;;
    en|en-US|en-GB) echo "English" ;;
    fr) echo "French" ;;
    es) echo "Spanish" ;;
    it) echo "Italian" ;;
    pt|pt-BR|pt-PT) echo "Portuguese" ;;
    ja) echo "Japanese" ;;
    ko) echo "Korean" ;;
    zh|zh-Hans|zh-Hant) echo "Chinese" ;;
    ar) echo "Arabic" ;;
    ru) echo "Russian" ;;
    sv) echo "Swedish" ;;
    nl) echo "Dutch" ;;
    pl) echo "Polish" ;;
    tr) echo "Turkish" ;;
    uk) echo "Ukrainian" ;;
    vi) echo "Vietnamese" ;;
    hi) echo "Hindi" ;;
    th) echo "Thai" ;;
    el) echo "Greek" ;;
    fi) echo "Finnish" ;;
    hu) echo "Hungarian" ;;
    cs) echo "Czech" ;;
    da) echo "Danish" ;;
    no|nb|nn) echo "Norwegian" ;;
    he) echo "Hebrew" ;;
    ro) echo "Romanian" ;;
    bg) echo "Bulgarian" ;;
    sk) echo "Slovak" ;;
    sl) echo "Slovenian" ;;
    et) echo "Estonian" ;;
    lt) echo "Lithuanian" ;;
    lv) echo "Latvian" ;;
    id) echo "Indonesian" ;;
    *) echo "$1" ;;
  esac
}

render_cmdline() {
  local args_json="$1"
  local out='<span class="prompt">$</span> translate'
  while IFS= read -r arg; do
    if [[ "$arg" == --* ]]; then
      out+=" <span class=\"flag\">$(echo "$arg" | html_escape)</span>"
    else
      out+=" <span class=\"arg\">$(echo "$arg" | html_escape)</span>"
    fi
  done < <(echo "$args_json" | jq -r '.[]')
  out+=" &lt; <span class=\"arg\">input.txt</span>"
  echo "$out"
}

# Render the source/translation pair for a normal translate JSON output.
render_translate_pair() {
  local json_file="$1"
  local items_json
  items_json=$(records_array "$json_file")

  local count
  count=$(echo "$items_json" | jq 'length')

  cat <<EOF
<div class="section-block">
  <div class="section-head">
    <span class="icon translate">⇄</span>
    <span class="label">Translation</span>
    <span class="stats">${count} record$([ "$count" -ne 1 ] && echo s || true)</span>
  </div>
EOF

  echo "$items_json" | jq -c '.[]' | while IFS= read -r row; do
    local from to src dst conf pct from_name to_name
    from=$(echo "$row" | jq -r '.from')
    to=$(echo "$row" | jq -r '.to')
    src=$(echo "$row" | jq -r '.src')
    dst=$(echo "$row" | jq -r '.dst')
    conf=$(echo "$row" | jq -r '.conf // 1')
    pct=$(awk "BEGIN { printf \"%.0f\", $conf * 100 }")
    from_name=$(lang_name "$from")
    to_name=$(lang_name "$to")
    cat <<EOF
  <div class="pair-grid" style="margin-bottom: 10px;">
    <div class="pair-cell src">
      <div class="lang">${from} &middot; $(echo "$from_name" | html_escape)</div>
      <div class="text">$(echo "$src" | html_escape)</div>
    </div>
    <div class="pair-cell dst">
      <div class="lang">${to} &middot; $(echo "$to_name" | html_escape)</div>
      <div class="text">$(echo "$dst" | html_escape)</div>
    </div>
  </div>
EOF
  done

  # Confidence summary (use the first record's confidence)
  local first_conf first_pct
  first_conf=$(echo "$items_json" | jq -r '.[0].conf // 1')
  first_pct=$(awk "BEGIN { printf \"%.1f\", $first_conf * 100 }")
  cat <<EOF
  <div class="pair-conf">
    <span>detection confidence</span>
    <span class="bar"><span class="fill" style="width:${first_pct}%"></span></span>
    <span>${first_pct}%</span>
  </div>
</div>
EOF
}

# Render the result of a --detect-only invocation.
render_detect_result() {
  local json_file="$1"
  local lang conf pct lang_name_str
  lang=$(jq -r '.detect.language' "$json_file")
  conf=$(jq -r '.detect.confidence' "$json_file")
  pct=$(awk "BEGIN { printf \"%.1f\", $conf * 100 }")
  lang_name_str=$(lang_name "$lang")
  cat <<EOF
<div class="section-block">
  <div class="section-head">
    <span class="icon detect">?</span>
    <span class="label">Language detection</span>
    <span class="stats">no translation</span>
  </div>
  <div class="detect-result">
    <div class="lang-line">
      <span class="lang-code">$(echo "$lang" | html_escape)</span>
      <span class="lang-name">$(echo "$lang_name_str" | html_escape)</span>
    </div>
    <div class="conf-line">
      <span>confidence</span>
      <span class="conf-bar"><span class="conf-fill" style="width:${pct}%"></span></span>
      <span>${pct}%</span>
    </div>
  </div>
</div>
EOF
}

build_card() {
  local idx="$1"
  local id title year category license source_url filename blurb args_json
  id=$(jq -r ".items[$idx].id" "$MANIFEST")
  title=$(jq -r ".items[$idx].title" "$MANIFEST")
  year=$(jq -r ".items[$idx].year" "$MANIFEST")
  category=$(jq -r ".items[$idx].category" "$MANIFEST")
  license=$(jq -r ".items[$idx].license" "$MANIFEST")
  source_url=$(jq -r ".items[$idx].source" "$MANIFEST")
  filename=$(jq -r ".items[$idx].filename" "$MANIFEST")
  blurb=$(jq -r ".items[$idx].blurb" "$MANIFEST")
  args_json=$(jq -c ".items[$idx].translate_args" "$MANIFEST")
  local source_text
  source_text=$(jq -r ".items[$idx].text" "$MANIFEST")

  local json_file="$DATA/$id.json"
  if [ ! -f "$json_file" ]; then return; fi

  local cmdline pretty title_e blurb_e license_e source_e source_text_e
  cmdline=$(render_cmdline "$args_json")
  pretty=$(pretty_json_file "$json_file" | html_escape)
  title_e=$(echo "$title" | html_escape)
  blurb_e=$(echo "$blurb" | html_escape)
  license_e=$(echo "$license" | html_escape)
  source_e=$(echo "$source_url" | html_escape)
  source_text_e=$(echo "$source_text" | html_escape)

  # Pick the right result renderer: --detect-only gets a different shape.
  local result_block
  if echo "$args_json" | jq -e 'index("--detect-only")' >/dev/null; then
    result_block=$(render_detect_result "$json_file")
  else
    result_block=$(render_translate_pair "$json_file")
  fi

  cat <<EOF
<article class="card" id="$id">
  <div class="card-text">$source_text_e</div>
  <div class="card-body">
    <div class="card-meta">
      <span class="badge $category">$category</span>
      <span>$year</span>
      <span>$license_e</span>
    </div>
    <h3>$title_e</h3>
    <p class="blurb">$blurb_e</p>
    <code class="cmd-line">$cmdline</code>
$result_block
    <div class="section-block">
      <div class="section-head">
        <span class="icon json">{}</span>
        <span class="label">Raw JSON</span>
        <span class="stats">on-device output</span>
      </div>
      <pre class="json-block">$pretty</pre>
    </div>
    <a class="source-link" href="$source_e" target="_blank" rel="noopener">Source</a>
  </div>
</article>
EOF
}

# ---- Compose ----
TMP_BODY=$(mktemp)
trap 'rm -f "$TMP_BODY"' EXIT

count=$(jq '.items | length' "$MANIFEST")
for i in $(seq 0 $((count - 1))); do
    id=$(jq -r ".items[$i].id" "$MANIFEST")
    printf "  %-40s built\n" "$id"
    build_card "$i" >> "$TMP_BODY"
done

# Compose the raw page first, THEN substitute placeholders. Placeholder
# values come from data/snippets/*.{cmd,out,wire} -- captured by
# scripts/run-snippets.py against a real translate --serve. Nothing on
# the page is hand-typed.
RAW_PAGE=$(mktemp)
trap 'rm -f "$TMP_BODY" "$RAW_PAGE"' EXIT
{
  cat "$TPL/header.html"
  cat "$TMP_BODY"
  cat "$TPL/footer.html"
} > "$RAW_PAGE"

# Inject the captured snippets via a Python helper (sed is unsafe with
# arbitrary JSON / quotes / newlines).
SNIPPETS_DIR="$ROOT/data/snippets"
python3 - "$RAW_PAGE" "$SNIPPETS_DIR" "$SITE/index.html" "$VERSION" "$TEST_COUNT" "$GENERATED" <<'PY'
import html, pathlib, re, sys

raw_path, snippets_dir, out_path, version, test_count, generated = sys.argv[1:7]
page = pathlib.Path(raw_path).read_text()
snip_dir = pathlib.Path(snippets_dir)

def read(name: str) -> str:
    p = snip_dir / name
    return p.read_text() if p.is_file() else f"# missing capture: {name}"

def html_escape(s: str) -> str:
    return html.escape(s)

# 1. CLI snippets -- one .cmd + .out merged into a colored shell snippet.
for cmd_file in sorted(snip_dir.glob("cli-*.cmd")):
    sid = cmd_file.stem.removeprefix("cli-")
    out = read(f"cli-{sid}.out").rstrip()
    cmd_line = read(f"cli-{sid}.cmd").rstrip()
    rendered = (
        '<span class="prompt">$</span> '
        + html_escape(cmd_line.removeprefix("$ ").rstrip())
        + "\n"
        + '<span class="out">' + html_escape(out) + "</span>"
    )
    page = page.replace(f"__SNIP_CLI_{sid}__", rendered)

# 2. Server snippets -- expose two placeholder shapes per id:
#      __SNIP_CMD_<id>__   ->  the curl one-liner
#      __SNIP_WIRE_<id>__  ->  the literal HTTP/1.1 response
for cmd_file in sorted(snip_dir.glob("server-*.cmd")):
    sid = cmd_file.stem.removeprefix("server-")
    cmd = read(f"server-{sid}.cmd").rstrip()
    wire = read(f"server-{sid}.wire").rstrip()
    page = page.replace(f"__SNIP_CMD_{sid}__", html_escape(cmd))
    page = page.replace(f"__SNIP_WIRE_{sid}__", html_escape(wire))

# 3. Compose the "Watch it work" terminal body from a curated CLI subset.
# Lead with the simplest positional-args form, then richer flows.
term_ids = ["hello-world-de-en", "args-en-de", "args-multi", "detect-fr", "ndjson-stream", "version"]
term_lines = []
for sid in term_ids:
    cmd = read(f"cli-{sid}.cmd").rstrip().removeprefix("$ ")
    out = read(f"cli-{sid}.out").rstrip()
    term_lines.append(
        '<span class="prompt">$</span> ' + html_escape(cmd) + "\n"
        '<span class="out">' + html_escape(out) + "</span>"
    )
page = page.replace("__SNIP_TERM_BODY__", "\n\n".join(term_lines))

# 4. Final scalar substitutions.
page = (page
    .replace("__VERSION__", version)
    .replace("__TEST_COUNT__", test_count)
    .replace("__GENERATED__", generated))

pathlib.Path(out_path).write_text(page)
PY

echo ""
echo "translate-web: site built at $SITE/index.html"
ls -lh "$SITE/index.html"
